# Generated by Django 5.1.3 on 2024-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_app', '0002_remove_stressdata_stress_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stressdata',
            name='user',
        ),
        migrations.AddField(
            model_name='stressdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='eye_movement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='limb_movement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='respiratory_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='sleep_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='snoring_rate',
            field=models.IntegerField(),
        ),
    ]
