# Generated by Django 5.1.3 on 2024-11-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_app', '0003_remove_stressdata_user_stressdata_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='blood_oxygen',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='eye_movement',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='limb_movement',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='snoring_rate',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='username',
        ),
        migrations.AddField(
            model_name='stressdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='gender',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='stress_level',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='work_hours',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='sleep_hours',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='user',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='stress_app.user'),
        ),
    ]
