# Generated by Django 5.1.3 on 2024-11-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_app', '0004_user_remove_stressdata_blood_oxygen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stressdata',
            name='user',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='stressdata',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='stressdata',
            name='blood_oxygen',
            field=models.FloatField(default=98.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='body_temperature',
            field=models.FloatField(default=36.5),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='eye_movement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='heart_rate',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='limb_movement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='respiratory_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='sleeping_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stressdata',
            name='snoring_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stressdata',
            name='stress_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
