# Generated by Django 5.1.3 on 2024-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_app', '0005_alter_stressdata_user_remove_stressdata_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressdata',
            name='is_stressed',
            field=models.BooleanField(default=False),
        ),
    ]
